language: c++
compiler: g++

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

install:
  - make get-deps

script:
  - make test
  - ./build/test

after_success:
  - make clean
