language: c++
compiler: g++

matrix:
  include:
    - os: osx
      osx_image: xcode10

before_install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade gcc -q
  - CC=gcc-7
  - CXX=g++-7

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install unittest-cpp -q

script:
  - make test
  - ./build/test

after_success:
  - make clean
