language: c++
compiler: g++

matrix:
  include:
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - brew install unittest-cpp

script:
  - make test
  - ./build/test

after_success:
  - make clean
